# Generated by Django 5.2.9 on 2026-04-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
            options={
                'verbose_name': 'Возможность',
                'verbose_name_plural': 'Возможности (лендинг)',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LandingContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(default='ERP для швейного производства', max_length=255, verbose_name='Бейдж над заголовком')),
                ('hero_title_line1', models.CharField(default='Производство сложное.', max_length=255, verbose_name='Заголовок (первая строка)')),
                ('hero_title_accent', models.CharField(default='Управлять им — проще.', max_length=255, verbose_name='Заголовок (акцентная строка)')),
                ('hero_subtitle', models.TextField(default='Управляйте швейным цехом с помощью нашего приложения. Получайте точные данные о производстве и сосредоточьтесь на том, что важно для бизнеса.', verbose_name='Подзаголовок под H1')),
                ('pricing_eyebrow', models.CharField(default='Связаться', max_length=255, verbose_name='Бейдж блока заявки')),
                ('pricing_title', models.CharField(default='Оптимизировать · Управлять · Процветать', max_length=255, verbose_name='Заголовок блока заявки')),
                ('pricing_text', models.TextField(default='Увеличьте эффективность и оптимизируйте процессы с нашим ERP. Оставьте заявку — подберём формат внедрения и стоимость.', verbose_name='Текст блока заявки')),
            ],
            options={
                'verbose_name': 'Контент лендинга',
                'verbose_name_plural': 'Контент лендинга',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='Телефон')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Обработана'), ('rejected', 'Отклонена')], db_index=True, default='new', max_length=32, verbose_name='Статус')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Заметки (только для админки)')),
                ('source', models.CharField(blank=True, default='landing', max_length=64, verbose_name='Источник')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
