# Generated by Django 5.2.9 on 2026-04-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_seed_capabilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='employee_count',
            field=models.PositiveIntegerField(blank=True, help_text='Число сотрудников на производстве (если указано)', null=True, verbose_name='Количество сотрудников'),
        ),
    ]
