# Generated by Django 5.2.9 on 2026-04-08 13:46

from django.db import migrations, models


def backfill_employee_band(apps, schema_editor):
    Lead = apps.get_model('website', 'Lead')
    for lead in Lead.objects.all():
        if lead.employee_band:
            continue
        c = lead.employee_count
        if c is None:
            continue
        if c <= 10:
            lead.employee_band = 'lt10'
        elif c <= 30:
            lead.employee_band = 'm10_30'
        elif c <= 100:
            lead.employee_band = 'm30_100'
        else:
            lead.employee_band = 'gt100'
        lead.save(update_fields=['employee_band'])


def sync_landing_pricing_copy(apps, schema_editor):
    LandingContent = apps.get_model('website', 'LandingContent')
    obj = LandingContent.objects.filter(pk=1).first()
    if not obj:
        return
    obj.pricing_eyebrow = ''
    obj.pricing_title = 'Начните прямо сейчас'
    obj.pricing_promo = 'Первые 14 дней — бесплатно'
    obj.pricing_text = (
        'Оставьте заявку — мы свяжемся в течение часа, настроим ваше рабочее пространство и ответим на все вопросы.'
    )
    obj.save()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_capabilities_six_truthful'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingcontent',
            name='pricing_promo',
            field=models.CharField(default='Первые 14 дней — бесплатно', max_length=255, verbose_name='Акцент под заголовком (блок заявки)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='employee_band',
            field=models.CharField(blank=True, choices=[('lt10', 'до 10'), ('m10_30', '10–30'), ('m30_100', '30–100'), ('gt100', 'более 100')], max_length=32, null=True, verbose_name='Количество сотрудников в цеху'),
        ),
        migrations.AlterField(
            model_name='landingcontent',
            name='hero_eyebrow',
            field=models.CharField(default='Система для швейного производства', max_length=255, verbose_name='Бейдж над заголовком'),
        ),
        migrations.AlterField(
            model_name='landingcontent',
            name='hero_subtitle',
            field=models.TextField(default='ШвейМетрикс — приложение для владельцев швейных цехов и фабрик. Контролируйте заказы, выработку сотрудников и расчёт зарплат в одном месте — в реальном времени.', verbose_name='Подзаголовок под H1'),
        ),
        migrations.AlterField(
            model_name='landingcontent',
            name='hero_title_accent',
            field=models.CharField(default='Управляйте цехом из телефона.', max_length=255, verbose_name='Заголовок (акцентная строка)'),
        ),
        migrations.AlterField(
            model_name='landingcontent',
            name='hero_title_line1',
            field=models.CharField(default='Забудьте про Excel.', max_length=255, verbose_name='Заголовок (первая строка)'),
        ),
        migrations.AlterField(
            model_name='landingcontent',
            name='pricing_eyebrow',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Бейдж блока заявки'),
        ),
        migrations.AlterField(
            model_name='landingcontent',
            name='pricing_text',
            field=models.TextField(default='Оставьте заявку — мы свяжемся в течение часа, настроим ваше рабочее пространство и ответим на все вопросы.', verbose_name='Текст блока заявки'),
        ),
        migrations.AlterField(
            model_name='landingcontent',
            name='pricing_title',
            field=models.CharField(default='Начните прямо сейчас', max_length=255, verbose_name='Заголовок блока заявки'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='employee_count',
            field=models.PositiveIntegerField(blank=True, help_text='Раньше вводилось числом; для новых заявок используйте диапазон.', null=True, verbose_name='Количество сотрудников (устар.)'),
        ),
        migrations.RunPython(backfill_employee_band, noop_reverse),
        migrations.RunPython(sync_landing_pricing_copy, noop_reverse),
    ]
